#!/bin/bash
# Recording Agent Layer - Post-Install Hook
# This script runs after the layer rootfs is extracted to the target image.
#
# Environment variables available:
#   LAYER_NAME - Name of this layer
#   LAYER_VERSION - Version of this layer
#   ROOTFS_PATH - Path to the mounted rootfs
#   CONFIG_VSOCK_PORT - Configured vsock port (default: 52)
#   CONFIG_BUFFER_SIZE_MB - Buffer size in MB (default: 16)
#   CONFIG_ENABLED - Whether recording is enabled (default: true)

set -euo pipefail

echo "[recording-agent] Running post-install hook..."

VSOCK_PORT="${CONFIG_VSOCK_PORT:-52}"
BUFFER_SIZE_MB="${CONFIG_BUFFER_SIZE_MB:-16}"
ENABLED="${CONFIG_ENABLED:-true}"

# Create directories
mkdir -p "${ROOTFS_PATH}/etc/nanofuse"
mkdir -p "${ROOTFS_PATH}/var/log/nanofuse"
mkdir -p "${ROOTFS_PATH}/var/lib/nanofuse/recordings"

# Create configuration file
cat > "${ROOTFS_PATH}/etc/nanofuse/record-agent.conf" << EOF
# NanoFuse Recording Agent Configuration
# Generated by post-install hook

[agent]
enabled = ${ENABLED}
vsock_port = ${VSOCK_PORT}
buffer_size_mb = ${BUFFER_SIZE_MB}

[capture]
modes = terminal,file_io
exclude_paths = /proc,/sys,/dev

[logging]
level = info
output = /var/log/nanofuse/record-agent.log
EOF

# Create systemd service file for recording agent
cat > "${ROOTFS_PATH}/etc/systemd/system/record-agent.service" << EOF
[Unit]
Description=NanoFuse Recording Agent
Documentation=https://github.com/daax-dev/nanofuse
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/record-agent --vsock-port ${VSOCK_PORT} --config /etc/nanofuse/record-agent.conf
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment=VSOCK_PORT=${VSOCK_PORT}
Environment=BUFFER_SIZE_MB=${BUFFER_SIZE_MB}

# Resource limits
MemoryMax=128M
CPUQuota=10%

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
ReadWritePaths=/var/log/nanofuse /var/lib/nanofuse

[Install]
WantedBy=multi-user.target
EOF

# Enable the service (will be applied at boot)
mkdir -p "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants"

if [[ "$ENABLED" == "true" ]]; then
    ln -sf /etc/systemd/system/record-agent.service \
        "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants/record-agent.service" 2>/dev/null || true
    echo "[recording-agent] Service enabled"
else
    rm -f "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants/record-agent.service" 2>/dev/null || true
    echo "[recording-agent] Service disabled by configuration"
fi

echo "[recording-agent] Configuration:"
echo "  vsock_port: ${VSOCK_PORT}"
echo "  buffer_size_mb: ${BUFFER_SIZE_MB}"
echo "  enabled: ${ENABLED}"
echo "[recording-agent] Recording agent layer installed successfully"
