#!/bin/bash
# Networking Tools Layer - Post-Install Hook
# This script runs after the layer rootfs is extracted to the target image.
#
# Environment variables available:
#   LAYER_NAME - Name of this layer
#   LAYER_VERSION - Version of this layer
#   ROOTFS_PATH - Path to the mounted rootfs
#   CONFIG_ENABLE_IPTABLES - Enable iptables (default: true)
#   CONFIG_ENABLE_NFTABLES - Enable nftables (default: true)
#   CONFIG_ENABLE_IP_FORWARDING - Enable IP forwarding (default: true)
#   CONFIG_DEFAULT_POLICY - Default firewall policy (default: drop)

set -euo pipefail

echo "[networking-tools] Running post-install hook..."

ENABLE_IPTABLES="${CONFIG_ENABLE_IPTABLES:-true}"
ENABLE_NFTABLES="${CONFIG_ENABLE_NFTABLES:-true}"
ENABLE_IP_FORWARDING="${CONFIG_ENABLE_IP_FORWARDING:-true}"
DEFAULT_POLICY="${CONFIG_DEFAULT_POLICY:-drop}"

# Create directories
mkdir -p "${ROOTFS_PATH}/etc/sysctl.d"
mkdir -p "${ROOTFS_PATH}/etc/nftables"

# Configure IP forwarding
if [[ "$ENABLE_IP_FORWARDING" == "true" ]]; then
    cat > "${ROOTFS_PATH}/etc/sysctl.d/99-gateway.conf" << EOF
# NanoFuse Gateway networking settings
# Generated by post-install hook

# Enable IPv4 forwarding
net.ipv4.ip_forward = 1
net.ipv4.conf.all.forwarding = 1

# Enable IPv6 forwarding
net.ipv6.conf.all.forwarding = 1

# Disable send redirects (security)
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Enable reverse path filtering
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable proxy ARP
net.ipv4.conf.all.proxy_arp = 0
EOF
    echo "[networking-tools] IP forwarding enabled"
else
    echo "[networking-tools] IP forwarding disabled"
fi

# Configure nftables service and policy
if [[ "$ENABLE_NFTABLES" == "true" ]]; then
    # Update nftables.conf with configured default policy
    if [[ -f "${ROOTFS_PATH}/etc/nftables.conf" ]]; then
        # Validate policy value (accept, drop, reject)
        case "${DEFAULT_POLICY}" in
            accept|drop|reject)
                # Valid policy; use as-is
                ;;
            *)
                echo "[networking-tools] Warning: invalid default_policy '${DEFAULT_POLICY}'; falling back to 'drop'" >&2
                DEFAULT_POLICY="drop"
                ;;
        esac
        # Update policy in all chains (input, forward, output), replacing any existing policy value.
        # Note: This sets the same policy for all chains. For fine-grained per-chain control,
        # edit /etc/nftables.conf directly after layer installation.
        # Pattern breakdown (GNU sed with -E flag for Extended Regular Expressions; uses POSIX ERE syntax, but sed -E itself is not POSIX, so not strictly portable):
        #   ^([[:space:]]*policy) - capture leading whitespace + "policy" at start of line
        #   [[:space:]]+          - one or more spaces/tabs between "policy" and value
        #   (accept|drop|reject)  - current policy value (POSIX ERE alternation group)
        # Replacement: captured group \1 (indent + "policy") + space + new policy value
        # This ensures "policy accept" becomes "policy drop" while preserving indentation.
        # Note: We require at least one space to avoid matching malformed lines like "policyaccept".
        sed -i -E "s/^([[:space:]]*policy)[[:space:]]+(accept|drop|reject)/\1 ${DEFAULT_POLICY}/" "${ROOTFS_PATH}/etc/nftables.conf"
        echo "[networking-tools] nftables default policy set to: ${DEFAULT_POLICY}"
    fi

    mkdir -p "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants"
    # Check if nftables.service exists before creating symlink
    if [[ -f "${ROOTFS_PATH}/lib/systemd/system/nftables.service" ]]; then
        if ! ln -sf /lib/systemd/system/nftables.service \
            "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants/nftables.service"; then
            echo "[networking-tools] Warning: failed to enable nftables.service symlink" >&2
        else
            echo "[networking-tools] nftables service enabled"
        fi
    else
        echo "[networking-tools] Warning: nftables.service not found; skipping service enablement" >&2
    fi
fi

echo "[networking-tools] Configuration:"
echo "  enable_iptables: ${ENABLE_IPTABLES}"
echo "  enable_nftables: ${ENABLE_NFTABLES}"
echo "  enable_ip_forwarding: ${ENABLE_IP_FORWARDING}"
echo "  default_policy: ${DEFAULT_POLICY}"
echo "[networking-tools] Networking tools layer installed successfully"
