#!/bin/bash
# Observability Layer - Post-Install Hook
# This script runs after the layer rootfs is extracted to the target image.
#
# Environment variables available:
#   LAYER_NAME - Name of this layer
#   LAYER_VERSION - Version of this layer
#   ROOTFS_PATH - Path to the mounted rootfs
#   CONFIG_NODE_EXPORTER_PORT - Node exporter port
#   CONFIG_ENABLE_STRUCTURED_LOGGING - Enable JSON logging
#   CONFIG_LOG_FORMAT - Log format
#   CONFIG_LOG_LEVEL - Log level

set -euo pipefail

echo "[observability] Running post-install hook..."

# Validate port is a number between 1-65535
validate_port() {
    local port="$1"
    if ! [[ "${port}" =~ ^[0-9]+$ ]] || [[ "${port}" -lt 1 ]] || [[ "${port}" -gt 65535 ]]; then
        echo "[observability] Error: Invalid port '${port}', must be 1-65535" >&2
        return 1
    fi
    return 0
}

# Validate positive integer with optional upper bound.
# Usage: validate_positive_int VALUE NAME [MAX_VALUE]
# Note: This function is duplicated in tls-certificates/hooks/post-install.sh with identical logic.
# Duplication is intentional: each layer's post-install hook must be self-contained since layers
# may be installed independently. A shared library would add complexity and cross-layer dependencies.
validate_positive_int() {
    local value="$1"
    local name="$2"
    local max_value="${3:-}"
    if ! [[ "${value}" =~ ^[0-9]+$ ]] || [[ "${value}" -lt 1 ]]; then
        echo "[observability] Error: ${name} must be a positive integer, got '${value}'" >&2
        return 1
    fi
    if [[ -n "${max_value}" ]] && [[ "${value}" -gt "${max_value}" ]]; then
        echo "[observability] Error: ${name} must be between 1 and ${max_value}, got '${value}'" >&2
        return 1
    fi
    return 0
}

NODE_EXPORTER_PORT="${CONFIG_NODE_EXPORTER_PORT:-9100}"
if ! validate_port "${NODE_EXPORTER_PORT}"; then
    echo "[observability] Using default port 9100" >&2
    NODE_EXPORTER_PORT="9100"
fi

ENABLE_STRUCTURED_LOGGING="${CONFIG_ENABLE_STRUCTURED_LOGGING:-true}"
LOG_FORMAT="${CONFIG_LOG_FORMAT:-json}"
LOG_LEVEL="${CONFIG_LOG_LEVEL:-info}"

RETENTION_DAYS="${CONFIG_RETENTION_DAYS:-7}"
if ! validate_positive_int "${RETENTION_DAYS}" "retention_days"; then
    echo "[observability] Using default retention 7 days" >&2
    RETENTION_DAYS="7"
fi

METRICS_PATH="${CONFIG_METRICS_PATH:-/metrics}"

# Create directories
mkdir -p "${ROOTFS_PATH}/etc/nanofuse"
mkdir -p "${ROOTFS_PATH}/var/log/nanofuse"

# Create logging configuration (using printf to avoid command substitution in config values)
{
  printf '%s\n' '# NanoFuse Logging Configuration'
  printf '%s\n' '# Generated by post-install hook'
  printf '\n'
  printf '%s\n' 'logging:'
  printf '  level: %s\n' "${LOG_LEVEL}"
  printf '  format: %s\n' "${LOG_FORMAT}"
  printf '  structured: %s\n' "${ENABLE_STRUCTURED_LOGGING}"
  printf '%s\n' '  outputs:'
  printf '%s\n' '    - type: file'
  printf '%s\n' '      path: /var/log/nanofuse/gateway.log'
  printf '%s\n' '    # stdout is captured by systemd journal (StandardOutput=journal)'
  printf '%s\n' '    # This provides both persistent logs (file) and real-time viewing (journalctl)'
  printf '%s\n' '    - type: stdout'
  printf '\n'
  printf '%s\n' 'rotation:'
  printf '%s\n' '  max_size_mb: 100'
  printf '  max_age_days: %s\n' "${RETENTION_DAYS}"
  printf '%s\n' '  max_backups: 5'
  printf '%s\n' '  compress: true'
} > "${ROOTFS_PATH}/etc/nanofuse/logging.yaml"

# Create node_exporter systemd service (using printf to avoid command substitution)
{
  printf '%s\n' '[Unit]'
  printf '%s\n' 'Description=Prometheus Node Exporter'
  printf '%s\n' 'Documentation=https://prometheus.io/docs/guides/node-exporter/'
  printf '%s\n' 'After=network.target'
  printf '\n'
  printf '%s\n' '[Service]'
  printf '%s\n' 'Type=simple'
  # Note: The exclude pattern filters pseudo-filesystem MOUNT POINTS (/sys, /proc) from
  # disk space metrics for the filesystem collector; it does not filter arbitrary paths.
  # /dev is NOT included in this exclusion: its devtmpfs mount is intentionally left
  # visible so that node_exporter can still report metrics for devices exposed there.
  # Device metrics (e.g., /dev/vda) primarily come from the diskstats collector, not
  # the filesystem collector.
  #
  # Pattern breakdown:
  #   --collector.filesystem.mount-points-exclude="^/(sys|proc)($|/)"
  #     Matches: /sys, /sys/*, /proc, /proc/* (pseudo-filesystems without meaningful
  #              disk-usage semantics for our purposes)
  #     Does NOT match: /dev (devtmpfs is a separate pseudo-filesystem and is not
  #              excluded by this pattern)
  #   --collector.netclass.ignored-devices="^(veth|docker|br-).*"
  #     Excludes container/bridge network interfaces from network metrics
  printf 'ExecStart=/usr/local/bin/node_exporter --web.listen-address=:%s --collector.filesystem.mount-points-exclude="^/(sys|proc)($|/)" --collector.netclass.ignored-devices="^(veth|docker|br-).*"\n' \
    "${NODE_EXPORTER_PORT}"
  printf '%s\n' 'Restart=always'
  printf '%s\n' 'RestartSec=5'
  printf '%s\n' 'StandardOutput=journal'
  printf '%s\n' 'StandardError=journal'
  printf '\n'
  printf '%s\n' '# Security hardening'
  printf '%s\n' '# ProtectKernelTunables keeps /proc/sys and related kernel tunables read-only'
  printf '%s\n' '# while still allowing node_exporter to read metrics (kernel stats, memory overcommit, etc.).'
  printf '%s\n' '# Node exporter only requires read access, so no additional ReadWritePaths exemptions are needed.'
  printf '%s\n' '# /sys and /proc remain read-only from the service perspective under this configuration.'
  printf '%s\n' 'NoNewPrivileges=yes'
  printf '%s\n' 'ProtectSystem=strict'
  printf '%s\n' 'ProtectHome=yes'
  printf '%s\n' 'PrivateTmp=yes'
  printf '%s\n' 'ProtectKernelTunables=yes'
  printf '%s\n' 'ProtectControlGroups=yes'
  printf '\n'
  printf '%s\n' '[Install]'
  printf '%s\n' 'WantedBy=multi-user.target'
} > "${ROOTFS_PATH}/etc/systemd/system/node-exporter.service"

# Enable the service
mkdir -p "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants"
if ! ln -sf /etc/systemd/system/node-exporter.service \
    "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants/node-exporter.service"; then
    echo "[observability] Warning: failed to create systemd symlink for node-exporter.service" >&2
fi

# Create logrotate configuration
mkdir -p "${ROOTFS_PATH}/etc/logrotate.d"
cat > "${ROOTFS_PATH}/etc/logrotate.d/nanofuse" << EOF
/var/log/nanofuse/*.log {
    daily
    rotate ${RETENTION_DAYS}
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root root
    sharedscripts
    # No postrotate required - NanoFuse gateway logs directly to files/stdout
}
EOF

echo "[observability] Configuration:"
echo "  node_exporter_port: ${NODE_EXPORTER_PORT}"
echo "  enable_structured_logging: ${ENABLE_STRUCTURED_LOGGING}"
echo "  log_format: ${LOG_FORMAT}"
echo "  log_level: ${LOG_LEVEL}"
echo "  retention_days: ${RETENTION_DAYS}"
echo "  metrics_path: ${METRICS_PATH}"
echo "[observability] Observability layer installed successfully"
