run:
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - bodyclose
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive

linters-settings:
  gocyclo:
    min-complexity: 20
  gosec:
    excludes:
      - G104
  staticcheck:
    checks:
      - "all"
      - "-QF*"
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-generated: lax
  exclude-rules:
    - linters:
        - errcheck
        - gosec
      path: _test\.go
    - linters:
        - revive
      path: cmd/
    - linters:
        - unused
      path: internal/api/
      text: "handle(VMs?|VM[A-Z]|VMBackups|Backup|VMSnapshots|Snapshot|Image|ImageJob)|extractIDFromPath"
  exclude-dirs:
    - third_party
    - builtin
    - examples
