#!/bin/bash
# Gateway Runtime Layer - Post-Install Hook
# This script runs after the layer rootfs is extracted to the target image.
#
# Environment variables available:
#   LAYER_NAME - Name of this layer
#   LAYER_VERSION - Version of this layer
#   ROOTFS_PATH - Path to the mounted rootfs
#   CONFIG_LISTEN_PORT - Main listener port (default: 8080)
#   CONFIG_METRICS_PORT - Metrics port (default: 9090)
#   CONFIG_HEALTH_PORT - Health port (default: 8081)

set -euo pipefail

echo "[gateway-runtime] Running post-install hook..."

LISTEN_PORT="${CONFIG_LISTEN_PORT:-8080}"
METRICS_PORT="${CONFIG_METRICS_PORT:-9090}"
HEALTH_PORT="${CONFIG_HEALTH_PORT:-8081}"
UPSTREAM_TIMEOUT="${CONFIG_UPSTREAM_TIMEOUT:-30s}"
MAX_CONNECTIONS="${CONFIG_MAX_CONNECTIONS:-10000}"
ENABLE_ACCESS_LOG="${CONFIG_ENABLE_ACCESS_LOG:-true}"

# Create directories
mkdir -p "${ROOTFS_PATH}/etc/nanofuse"
mkdir -p "${ROOTFS_PATH}/var/log/nanofuse/gateway"

# Create configuration file (using printf to avoid command substitution in config values)
{
  printf '%s\n' '# NanoFuse Gateway Configuration'
  printf '%s\n' '# Generated by post-install hook'
  printf '\n'
  printf '%s\n' 'server:'
  printf '  listen_port: %s\n' "${LISTEN_PORT}"
  printf '  metrics_port: %s\n' "${METRICS_PORT}"
  printf '  health_port: %s\n' "${HEALTH_PORT}"
  printf '\n'
  printf '%s\n' 'routing:'
  printf '  upstream_timeout: %s\n' "${UPSTREAM_TIMEOUT}"
  printf '  max_connections: %s\n' "${MAX_CONNECTIONS}"
  printf '  enable_access_log: %s\n' "${ENABLE_ACCESS_LOG}"
  printf '\n'
  # TLS configuration (requires tls-certificates layer when enabled)
  # Note: To enable TLS, set enabled: true and ensure tls-certificates layer is included
  printf '%s\n' 'tls:'
  printf '%s\n' '  enabled: false'
  printf '%s\n' '  cert_file: /etc/nanofuse/certs/server.crt'
  printf '%s\n' '  key_file: /etc/nanofuse/certs/server.key'
  printf '\n'
  printf '%s\n' 'logging:'
  printf '%s\n' '  level: info'
  printf '%s\n' '  format: json'
  printf '%s\n' '  output: /var/log/nanofuse/gateway/access.log'
} > "${ROOTFS_PATH}/etc/nanofuse/gateway.yaml"
# Mode 0640: owner (root) rw, group (root) r, others none
# The gateway service runs as root but group read is preserved for
# flexibility if the service is later configured to run as a non-root user
chmod 0640 "${ROOTFS_PATH}/etc/nanofuse/gateway.yaml"

# Create systemd service file (using printf to avoid command substitution in config values)
{
  printf '%s\n' '[Unit]'
  printf '%s\n' 'Description=NanoFuse Gateway Service'
  printf '%s\n' 'Documentation=https://github.com/peregrinesummit/nanofuse'
  printf '%s\n' 'After=network.target nftables.service'
  printf '%s\n' 'Wants=network.target'
  printf '\n'
  printf '%s\n' '[Service]'
  printf '%s\n' 'Type=simple'
  printf 'ExecStart=/usr/local/bin/nanofuse-gateway --listen-port %s --metrics-port %s --health-port %s --config /etc/nanofuse/gateway.yaml\n' \
    "${LISTEN_PORT}" "${METRICS_PORT}" "${HEALTH_PORT}"
  printf '%s\n' 'Restart=always'
  printf '%s\n' 'RestartSec=5'
  printf '%s\n' 'StandardOutput=journal'
  printf '%s\n' 'StandardError=journal'
  printf '\n'
  printf '%s\n' '# Resource limits'
  printf '%s\n' '# MemoryMax=512M: Conservative limit for gateway in microVM context (typically 1GB total)'
  printf '%s\n' '# max_connections=10000 is achievable with ~50KB per connection overhead (~500MB peak)'
  printf '%s\n' '# Adjust MemoryMax based on actual VM sizing if higher concurrency is needed'
  printf '%s\n' 'MemoryMax=512M'
  printf '%s\n' 'CPUQuota=50%'
  printf '\n'
  printf '%s\n' '# Security hardening'
  printf '%s\n' '# Note: ProtectSystem=strict makes filesystem read-only except allowed paths'
  printf '%s\n' '# Configuration changes require "systemctl restart nanofuse-gateway" to take effect'
  printf '%s\n' '# (the Go gateway binary reads config at startup; no runtime reload is supported)'
  printf '%s\n' 'NoNewPrivileges=yes'
  printf '%s\n' 'ProtectSystem=strict'
  printf '%s\n' 'ProtectHome=yes'
  printf '%s\n' 'PrivateTmp=yes'
  printf '%s\n' 'ProtectKernelTunables=yes'
  printf '%s\n' 'ProtectControlGroups=yes'
  printf '%s\n' 'ReadWritePaths=/var/log/nanofuse'
  printf '%s\n' 'CapabilityBoundingSet='
  printf '%s\n' 'AmbientCapabilities='
  # Note: /etc/nanofuse is already read-only via ProtectSystem=strict
  # Note: All Linux capabilities are dropped by default because the gateway only
  #       listens on unprivileged ports (>1024). If you configure any gateway
  #       port to use a privileged port (<1024), update the systemd unit to add
  #       AmbientCapabilities=CAP_NET_BIND_SERVICE and a corresponding
  #       CapabilityBoundingSet (e.g. CAP_NET_BIND_SERVICE) instead of leaving it empty.
  printf '\n'
  printf '%s\n' '[Install]'
  printf '%s\n' 'WantedBy=multi-user.target'
} > "${ROOTFS_PATH}/etc/systemd/system/nanofuse-gateway.service"

# Enable the service
mkdir -p "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants"
if ! ln -sf /etc/systemd/system/nanofuse-gateway.service \
    "${ROOTFS_PATH}/etc/systemd/system/multi-user.target.wants/nanofuse-gateway.service"; then
    echo "[gateway-runtime] Warning: failed to create systemd symlink for nanofuse-gateway.service" >&2
fi

echo "[gateway-runtime] Configuration:"
echo "  listen_port: ${LISTEN_PORT}"
echo "  metrics_port: ${METRICS_PORT}"
echo "  health_port: ${HEALTH_PORT}"
echo "  upstream_timeout: ${UPSTREAM_TIMEOUT}"
echo "  max_connections: ${MAX_CONNECTIONS}"
echo "[gateway-runtime] Gateway runtime layer installed successfully"
